version: "3"
services:
  app:
    container_name: "app"
    volumes:
      - .:/go/src/app:cached
      - /tmp/.X11-unix:/tmp/.X11-unix
    tty: true
    command: /bin/bash
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY=${HOSTNAME}:0
